version: "3.7"

services:
  qtweet:
    build: .
    image: navenn_t/qtweet
    volumes:
      - qtweetData:/usr/src/app/data/
    environment:
      - TZ=Europe/Paris
    container_name: qtweet

volumes:
  qtweetData:
    external: true
